name: Build STM32 CMake Project

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
# Step1: Checkout code
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: true
        
# Step2: Build with STM32CubeCLT
        - name: Build with STM32CubeCLT
          uses: uoohyo/action-stm32-cmake@v1.21.0
          with:
            project-path: '.'
            build-config: 'Release'
            build-target: 'all'

# Step3: Upload build artifacts
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-artifacts
            path: |
              build/Release/*.elf
              build/Release/*.bin
              build/Release/*.hex
            retention-days: 1